version: '3.7'
services:
 zookeeper:
   container_name: zookeeper_container
   image: confluentinc/cp-zookeeper:5.2.1
   environment:
     ZOOKEEPER_CLIENT_PORT: 2181
     ZOOKEEPER_TICK_TIME: 2000
     ZOOKEEPER_SYNC_LIMIT: 2

 kafka:
   container_name: kafka_container
   image: confluentinc/cp-kafka:5.2.1
   ports:
    - "9092:9092"
   depends_on:
    - zookeeper
   environment:
     KAFKA_BROKER_ID: 1
     KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
     KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
     KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
     KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"

 mysql_cliente:
  container_name: mysql_cliente
  image: mysql:5.7
  restart: always
  environment:
    MYSQL_DATABASE: 'dbcliente'
    MYSQL_USER: 'cliente'
    MYSQL_PASSWORD: 'cliente'
    MYSQL_ROOT_PASSWORD: 'root'
  ports:
   - '3306:3306'
  expose:
   - '3306'
