version: "3"

services:

  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: santander
    ports:
      - 3306:3306


  solr:
    image: andrehenriques/solr:v1
    container_name: solr
    ports:
      - 8983:8983


  rabbitmq: 
    image: rabbitmq:3.6.15-management-alpine
    container_name: rabbitmq
    ports:
      - 15672:15672
      - 5672:5672


  eureka:
    build: ./core/core.registry
    container_name: eureka
    ports:
      - 8761:8761


  zuul:
    build: ./core/core.gateway
    container_name: zuul
    ports:
      - 8443:8443
    environment:
      EUREKA_IP: eureka
    depends_on:
      - eureka


  sale-worker:
    build: ./app/sale-worker
    environment:
      MYSQL_IP: mysql
      SOLR_IP: solr
      RABBITMQ_IP: rabbitmq


  sale-api:
    build: ./app/sale
    environment:
      EUREKA_IP: eureka
      RABBITMQ_IP: rabbitmq
    depends_on:
      - rabbitmq
      - sale-worker 

      
  client-api:
    build: ./app/client
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sandater
      EUREKA_IP: eureka
      MYSQL_IP: mysql
      SOLR_IP: solr
      RABBITMQ_IP: rabbitmq
    depends_on:
      - rabbitmq
      - mysql
      - solr
      - eureka
      - sale-worker # Esse serviço cria as tabelas no banco e a fila