version: '3'
services:
  gastos:
    container_name: gastos-v1
    image:  gastos-v1:latest  
    ports:
      - '8080:8080'
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo:3.4.6
    ports: 
      - '27017:27017'
