version: '2.2'
services:
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.3
    container_name: es01
    environment:
      - node.name=es01
      - discovery.seed_hosts=es02
      - cluster.initial_master_nodes=es01,es02
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - net-classification
  es02:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.3
    container_name: es02
    environment:
      - node.name=es02
      - discovery.seed_hosts=es01
      - cluster.initial_master_nodes=es01,es02
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata02:/usr/share/elasticsearch/data
    networks:
      - net-classification

#  santander-classification:
#    depends_on:
#      - mysql
#      - redis
#    links:
#      - mysql
#    environment:
#      SPRING_REDIS_HOST: redis
#      SPRING_DATASOURCE_URL: "jdbc:mysql://mysql:3306/gastos"
#    networks:
#      - net-classification
#    build:
#      context: .
#    container_name: classification-app
#    ports:
#      - "9401:8080"

volumes:
  esdata01:
    driver: local
  esdata02:
    driver: local

networks:
  net-classification:
    driver: bridge