version: '3.3'

services:
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'gastos'
      MYSQL_USER: 'gastos'
      MYSQL_PASSWORD: 'gastos'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql

  redis:
    image: redis
    command: redis-server --requirepass Redis2019!
    ports:
      - "6379:6379"

  mongo:
    image: mongo
    ports:
      - "27017:27017"

volumes:
  my-db: