CREATE TABLE "USUARIO"
(
    "ID"    BIGINT AUTO_INCREMENT PRIMARY KEY,
    "NOME"  TEXT   NOT NULL,
    "LOGIN" TEXT   NOT NULL,
    "SENHA" TEXT   NOT NULL,
    "TIPO"  INTEGER NOT NULL,
);

CREATE TABLE "PERFIL"
(
    "ID"    BIGINT AUTO_INCREMENT PRIMARY KEY,
    "NOME"  TEXT   NOT NULL
);


INSERT INTO "USUARIO" ("NOME", "LOGIN", "SENHA", "TIPO") VALUES ( 'Administrador','admin','$2a$10$.ltOnHeuxrc2JLpiG8Ex0.1MT/L2Ah2faemk6DCR.yZAhK6yt2fve',1);
INSERT INTO "USUARIO" ("NOME", "LOGIN", "SENHA", "TIPO") VALUES ( 'Usuario','user','$2a$10$oLSlGuWbD43fYrw.7DzkQubr2Q8Ronbnw8r1zpkjTHzJsQ6z5oXPq',2);
INSERT INTO "USUARIO" ("NOME", "LOGIN", "SENHA", "TIPO") VALUES ( 'Sistema','sys','$2a$10$opBp5R5Cvje.VC/jwNTuLOucdUbKpue9kEzA5gSdYEYzZ6Eb/M.Cq',1);
