
INSERT INTO CATEGORIA (ID, DESCRICAO) VALUES (1, 'teste');

INSERT INTO USUARIO (ID, NOME, ROLE) VALUES (1, 'user', 'admin'); 

INSERT INTO GASTO (ID,DATA,DESCRICAO,ID_USUARIO,ID_CATEGORIA) VALUES (1, SYSDATE, 'Gasto teste 1', 1,1);
INSERT INTO GASTO (ID,DATA,DESCRICAO,ID_USUARIO,ID_CATEGORIA) VALUES (2, SYSDATE, 'Gasto teste 2', 1,1);
INSERT INTO GASTO (ID,DATA,DESCRICAO,ID_USUARIO,ID_CATEGORIA) VALUES (3, SYSDATE, 'Gasto teste 3', 1,1);