CREATE TABLE CATEGORIA(
	ID NUMBER PRIMARY KEY,
	DESCRICAO VARCHAR(25)
);

CREATE TABLE USUARIO(
	ID NUMBER PRIMARY KEY,
	NOME VARCHAR(25),
	ROLE VARCHAR(25)
);

CREATE TABLE GASTO(
  ID NUMBER	 PRIMARY KEY,
  DESCRICAO VARCHAR(25),
  VALOR FLOAT,
  ID_USUARIO NUMBER,
  ID_CATEGORIA NUMBER,
  DATA DATE
);

ALTER TABLE GASTO ADD FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID);

ALTER TABLE GASTO ADD FOREIGN KEY (ID_CATEGORIA) REFERENCES CATEGORIA(ID);
