server:
  port: 8083

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  profiles:
    active: default      
  datasource: 
    username: root
    password: root
    url: jdbc:mysql://localhost:6033/db_usuarios 
  application:
    name: 'usuarios'
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
      
security:
  oauth2:
    resource:
      user-info-uri: http://localhost:8090/user
      
     
flyway:
   url: jdbc:mysql://localhost:6033/db_usuarios 
   schemas: db_usuarios
   user: "root"
   password: "root"           