server:
  port: 8081

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-service:8761/eureka

spring:
  profiles:
    active: default      
  datasource: 
    username: root
    password: root
    url: jdbc:mysql://mysql-categorias:3306/db_categorias 
  application:
    name: 'categorias'
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
security:
  oauth2:
    resource:
      user-info-uri: http://auth-service:8090/user   
      

flyway:
   url: jdbc:mysql://mysql-categorias:3306/db_categorias
   schemas: db_categorias
   user: "root"
   password: "root"