server:
  port: 8081

spring:
  application:
    name: 'cliente'
  
  h2:
    console:
      enabled: true
      path: /h2-console
      
  datasource:
    url: jdbc:h2:file:~/teste
    username: sa
    password: 
    driver-class-name: org.h2.Driver
    
  jpa:
    show-sql: true
    
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
      
security:
  oauth2:
    resource:
      user-info-uri: http://localhost:8088/user
      

  