spring:
  application:
    name: gastos
  
  h2:
    console:
      enabled: true
      path: /h2-console
      
  datasource:
    url: jdbc:h2:file:~/test
    username: sa
    password: 
    driver-class-name: org.h2.Driver
    
  jpa:
    show-sql: true
    
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

  